# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
uploaded = files.upload()

# =========================================
# E-commerce Sales Analysis
# =========================================

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# =========================================
# 1. LOAD DATA
# =========================================
uploaded = files.upload()

data = pd.read_csv("sales_data.csv")

# =========================================
# 2. DATA CLEANING
# =========================================
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)
data['Order Date'] = pd.to_datetime(data['Order Date'])

# =========================================
# 3. FEATURE ENGINEERING
# =========================================
data['Total Sales'] = data['Price'] * data['Quantity']
data['Month'] = data['Order Date'].dt.month

# =========================================
# 4. ANALYSIS
# =========================================
monthly_sales = data.groupby('Month')['Total Sales'].sum()
category_sales = data.groupby('Category')['Total Sales'].sum()

# =========================================
# 5. VISUALIZATIONS
# =========================================

plt.style.use('seaborn-v0_8')

pastel_blue = '#a7c7e7'
pastel_purple = '#cbaacb'
pastel_pink = '#f4c2c2'

# ---------- LINE CHART ----------
plt.figure(figsize=(6,3.5))
plt.plot(monthly_sales.index, monthly_sales.values,
         marker='o', linewidth=2.5, color=pastel_blue)

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ---------- BAR CHART ----------
plt.figure(figsize=(6,3.5))
plt.bar(category_sales.index, category_sales.values,
        color=[pastel_purple, pastel_pink],
        edgecolor='black')

plt.title('Sales by Category')
plt.xlabel('Category')
plt.ylabel('Revenue')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ---------- PIE CHART ----------
plt.figure(figsize=(4.5,4.5))
plt.pie(category_sales.values,
        labels=category_sales.index,
        autopct='%1.1f%%',
        colors=[pastel_purple, pastel_pink])

plt.title('Sales Distribution')
plt.tight_layout()
plt.show()

# =========================================
# 6. INSIGHTS
# =========================================
print("\n KEY INSIGHTS:")
print(f"✔ Best category: {category_sales.idxmax()}")
print(f"✔ Highest sales month: {monthly_sales.idxmax()}")
print("✔ Sales show a clear monthly trend")
print("✔ Category contribution is clearly visible from the pie chart")

print("\n🎉 Project completed successfully!")