# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
uploaded= files.upload()

# ------------------------------
# CLEAN MINIMAL VISUALS (NO EXTRA TEXT)
# ------------------------------

plt.style.use('seaborn-v0_8')

pastel_blue = '#a7c7e7'
pastel_purple = '#cbaacb'
pastel_pink = '#f4c2c2'

# ---------- LINE CHART ----------
plt.figure(figsize=(6,3.5))  # smaller size

plt.plot(monthly_sales.index, monthly_sales.values,
         marker='o', linewidth=2.5, color=pastel_blue)

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Revenue')

plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()


# ---------- BAR CHART ----------
plt.figure(figsize=(6,3.5))

plt.bar(category_sales.index, category_sales.values,
        color=[pastel_purple, pastel_pink],
        edgecolor='black')

plt.title('Sales by Category')
plt.xlabel('Category')
plt.ylabel('Revenue')

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()


# ---------- PIE CHART ----------
plt.figure(figsize=(4.5,4.5))

plt.pie(category_sales.values,
        labels=category_sales.index,
        autopct='%1.1f%%',
        colors=[pastel_purple, pastel_pink])

plt.title('Sales Distribution')

plt.tight_layout()
plt.show()

# ------------------------------
# 6. Insights
# ------------------------------

print("\n KEY INSIGHTS:")
print(f"✔ Best category: {category_sales.idxmax()}")
print(f"✔ Highest sales month: {monthly_sales.idxmax()}")
print("✔ Sales show a clear monthly trend")
print("✔ Category contribution is clearly visible from the pie chart")

print("\n🎉 Project completed successfully!")